### PR TITLE
fix: casbin gorm-adapter has no sqlite3 support

### PR DESCRIPTION
**Pull request by closetool**
Signed-off-by: closetool <c299999999@qq.com>

Fix: #407

更改了casbin,gorm-adapter的版本, 删除了casbin v1

### CODE REVIEW

**Comment by closetool** [comment]
@hsluoyz @piexlmax @ma3315865 fixed, plz review

**Comment by piexlmax** [comment]
请提交到develop分支方便合并

**Comment by hsluoyz** [comment]
@closetool

**Comment by hsluoyz** [comment]
Replaced by: https://github.com/flipped-aurora/gin-vue-admin/pull/426

@closetool plz close this PR.

**Pull request closed without merging**
